# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/cgonzalez/Programming Projects/Assignments/Class Project/Connect-4-Class-Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/cgonzalez/Programming Projects/Assignments/Class Project/Connect-4-Class-Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cgonzalez/Programming Projects/Assignments/Class Project/Connect-4-Class-Project/CMakeFiles" "/home/cgonzalez/Programming Projects/Assignments/Class Project/Connect-4-Class-Project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cgonzalez/Programming Projects/Assignments/Class Project/Connect-4-Class-Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named COP_II

# Build rule for target.
COP_II: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 COP_II
.PHONY : COP_II

# fast build rule for target.
COP_II/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/build
.PHONY : COP_II/fast

#=============================================================================
# Target rules for targets named COP_II_autogen_timestamp_deps

# Build rule for target.
COP_II_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 COP_II_autogen_timestamp_deps
.PHONY : COP_II_autogen_timestamp_deps

# fast build rule for target.
COP_II_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II_autogen_timestamp_deps.dir/build.make CMakeFiles/COP_II_autogen_timestamp_deps.dir/build
.PHONY : COP_II_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named COP_II_autogen

# Build rule for target.
COP_II_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 COP_II_autogen
.PHONY : COP_II_autogen

# fast build rule for target.
COP_II_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II_autogen.dir/build.make CMakeFiles/COP_II_autogen.dir/build
.PHONY : COP_II_autogen/fast

COP_II_autogen/mocs_compilation.o: COP_II_autogen/mocs_compilation.cpp.o
.PHONY : COP_II_autogen/mocs_compilation.o

# target to build an object file
COP_II_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/COP_II_autogen/mocs_compilation.cpp.o
.PHONY : COP_II_autogen/mocs_compilation.cpp.o

COP_II_autogen/mocs_compilation.i: COP_II_autogen/mocs_compilation.cpp.i
.PHONY : COP_II_autogen/mocs_compilation.i

# target to preprocess a source file
COP_II_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/COP_II_autogen/mocs_compilation.cpp.i
.PHONY : COP_II_autogen/mocs_compilation.cpp.i

COP_II_autogen/mocs_compilation.s: COP_II_autogen/mocs_compilation.cpp.s
.PHONY : COP_II_autogen/mocs_compilation.s

# target to generate assembly for a file
COP_II_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/COP_II_autogen/mocs_compilation.cpp.s
.PHONY : COP_II_autogen/mocs_compilation.cpp.s

Connect4.o: Connect4.cpp.o
.PHONY : Connect4.o

# target to build an object file
Connect4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/Connect4.cpp.o
.PHONY : Connect4.cpp.o

Connect4.i: Connect4.cpp.i
.PHONY : Connect4.i

# target to preprocess a source file
Connect4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/Connect4.cpp.i
.PHONY : Connect4.cpp.i

Connect4.s: Connect4.cpp.s
.PHONY : Connect4.s

# target to generate assembly for a file
Connect4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/Connect4.cpp.s
.PHONY : Connect4.cpp.s

battleship.o: battleship.cpp.o
.PHONY : battleship.o

# target to build an object file
battleship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/battleship.cpp.o
.PHONY : battleship.cpp.o

battleship.i: battleship.cpp.i
.PHONY : battleship.i

# target to preprocess a source file
battleship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/battleship.cpp.i
.PHONY : battleship.cpp.i

battleship.s: battleship.cpp.s
.PHONY : battleship.s

# target to generate assembly for a file
battleship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/battleship.cpp.s
.PHONY : battleship.cpp.s

boardgrid.o: boardgrid.cpp.o
.PHONY : boardgrid.o

# target to build an object file
boardgrid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/boardgrid.cpp.o
.PHONY : boardgrid.cpp.o

boardgrid.i: boardgrid.cpp.i
.PHONY : boardgrid.i

# target to preprocess a source file
boardgrid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/boardgrid.cpp.i
.PHONY : boardgrid.cpp.i

boardgrid.s: boardgrid.cpp.s
.PHONY : boardgrid.s

# target to generate assembly for a file
boardgrid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/boardgrid.cpp.s
.PHONY : boardgrid.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/COP_II.dir/build.make CMakeFiles/COP_II.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... COP_II_autogen"
	@echo "... COP_II_autogen_timestamp_deps"
	@echo "... COP_II"
	@echo "... COP_II_autogen/mocs_compilation.o"
	@echo "... COP_II_autogen/mocs_compilation.i"
	@echo "... COP_II_autogen/mocs_compilation.s"
	@echo "... Connect4.o"
	@echo "... Connect4.i"
	@echo "... Connect4.s"
	@echo "... battleship.o"
	@echo "... battleship.i"
	@echo "... battleship.s"
	@echo "... boardgrid.o"
	@echo "... boardgrid.i"
	@echo "... boardgrid.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

